### ISSUE TITLE
MachineTelemetryData inconsistent naming with TelemetryData

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#141]
I am putting together some generic Kusto queries for observer data and have one property name tripping me up slightly.

It seems the general convention is a 'Node' property  on ETW data but 'NodeName' on Telemetry Data (which ends up in App Insights).

Is it expected, or is it possible for the 'Node' property on the MachineTelemetryData class to match the TelemetryData class 
'NodeName'?

**Comment by GitTorre** [comment]
Thanks. I will merge naming scheme to make it more consistent. 

For MachineTelemetryData it will be this:

ActiveEphemeralTcpPorts 
ActiveFirewallRules 
ActiveTcpPorts 
AvailablePhysicalMemory 
AvailableVirtualMemory 
DriveInfo 
FabricAppPortRange 
HotFixes 
LastBootUpTime 
Level 
LogicalDriveCount 
LogicalProcessorCount 
NodeName 
NumberOfRunningProcesses 
ObserverName 
OS 
OSInstallDate 
OSVersion 
TotalMemorySizeGB 
WindowsDynamicPortRange

**Comment by GitTorre** [comment]
Actually,the final namings will be slightly different than above. I will push changes to develop next week including other changes unrelated to this. Thanks for the report.

**Comment by adamtickner** [comment]
Great - I will keep an eye out for the next release.

**Comment by GitTorre** [comment]
Pushed to develop: https://github.com/microsoft/service-fabric-observer/blob/develop/FabricObserver.Extensibility/Utilities/Telemetry/MachineTelemetryData.cs 

Does that naming scheme work for you?

**Comment by adamtickner** [comment]
Looks good to me!

Will the log properties remain consistent now or is there likely to be a specific release where they might remain locked? 

I see there are a few changes in there (eg Source -> ObserverName, Application -> Application Name, Service -> ServiceName, AvailableVirtualMemoryGB -> FreeVirtualMemoryGB and a couple of others).

**Comment by GitTorre** [comment]
No changes were made to TelemetryData and only OSObserver employs MachineTelemetryData. So, this is why it was somewhat left behind... The ones that ship for MTD in 3.1.11 are not going to change. There are members in MTD that do not exist in TD, of course, so no changes were made to TD. This will remain "locked" as renaming things should not be a common practice for telemetry data types.

**Comment by GitTorre** [comment]
The changes that were made were done to better describe the metric (and have meaning across Linux and Windows). Also, your suggestion to append Name to Node was taken for Application and Service to match TelemetryData's impl.

**Comment by adamtickner** [comment]
Perfect, thank you.
