### ISSUE TITLE
OSObserver reporting hot fixes unformatted to app insights

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#150]
**Description**
App insights is now reporting hotfixes in a hyper link format, rather than a simple list as in the previous release.

**To Reproduce**
Report OSObserver to app insights and observe in the log search, shown in attached screenshot.

**Expected behavior**
Hot fixes to report in a simple list as before, KX111, KX222 etc

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Windows 10 
![os-observer](https://user-images.githubusercontent.com/5872717/118760704-9c410e80-b8b6-11eb-86c5-27e4fc18afeb.PNG)

**Additional context**
Happening since upgrading to the most recent release, [3.1.11](url)

**Comment by GitTorre** [comment]
Thanks for catching this. Hyperlink removal happens for ETW only in this release, which is a bug: they should be removed for all telemetry types. This fix will ship in the next version.

**Comment by GitTorre** [comment]
Please verify using this release: https://github.com/microsoft/service-fabric-observer/releases/tag/42723786 

You should no longer see hyperlinks in MachineTelemetryData's HotFixes property.
