### ISSUE TITLE
[BUG] CPU Usage increased 30% coming from build 3.0.8 to 3.1.15

### ISSUE THREAD

**Issue by davidleacy** [microsoft/service-fabric-observer#158]
**Overview**
Hi Team, we recently updated our FabricObserver version from `3.0.8` to `3.1.15` and this correlates with a large 25-30% increase in CPU usage across all our clusters.

We tried increase the `ObserverLoopSleepTimeSeconds` from `30` seconds to `120` seconds this decreased usage by 10%.

Looking for advice on how we can reduce this further and get performance similar to `3.0.8`. Presumably, more components have been added since then but it's hard as a user to understand where the perf hits may be coming from.

Thanks for your help.

**To Reproduce**
Upgrade from `3.0.8` to `3.1.15`.

**Expected behavior**
A significantly smaller increase in CPU usage.

**Screenshots**
CPU Charts showing the increase after update and subsequent decrease after increasing `ObserverLoopSleepTimeSeconds` to 120 seconds
![image](https://user-images.githubusercontent.com/9117924/126625869-b10a56c2-78ea-47b8-aec0-c924f3fe64a4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Windows Server 2019 (Azure)

**Additional context**

Settings we have changed compared to the default [Settings.xml](https://github.com/microsoft/service-fabric-observer/blob/main/FabricObserver/PackageRoot/Config/Settings.xml)
``` xml
<Parameter Name="ObserverLoopSleepTimeSeconds" Value="120" />
<Parameter Name="ObserverExecutionTimeout" Value="1800" />
<Parameter Name="EnableVerboseLogging" Value="true" />
```

Settings we have changed compared to the default [ApplicationManifest.xml](https://github.com/microsoft/service-fabric-observer/blob/main/FabricObserverApp/ApplicationPackageRoot/ApplicationManifest.xml)
``` xml
<Parameter Name="AppObserverEnableEtw" DefaultValue="true" />
<Parameter Name="CertificateObserverEnableEtw" DefaultValue="true" />
<Parameter Name="DiskObserverEnableEtw" DefaultValue="true" />
<Parameter Name="FabricSystemObserverEnableEtw" DefaultValue="true" />
<Parameter Name="NetworkObserverEnableEtw" DefaultValue="true" />
<Parameter Name="NodeObserverEnableEtw" DefaultValue="true" />
<Parameter Name="OSObserverEnableEtw" DefaultValue="true" />
<Parameter Name="SFConfigurationObserverEnableEtw" DefaultValue="true" />
```

**Comment by GitTorre** [comment]
Thanks for the report. I am testing with these settings now and do not see any CPU overhead with all observers also enabled. 

Can you send me your Settings.xml and ApplicationManifest.xml files? 

For sure, 3.1.15 does more than 3.0.8 did (that version is not supported and I'm glad you upgraded) but not at the cost of CPU you are seeing. Further, when FO sleeps, it is not doing anything, so CPU use would be 0. I don't understand why it is computing when sleeping, based on your graphic. I will need to know more about your setup and settings. Please do contact me directly with details.

**Comment by GitTorre** [comment]
Interestingly, I am noticing that Windows Defender's anti-virus scanner kicks in every time FO wakes up and does work. It is unclear to me why Defender is stalking FabricObserver. I have sent a note to the Windows Defender team to get some help figuring this out. It is quite unfortunate. This is net new misbehavior by Defender. I have not seen this before and I am not seeing it in my own test clusters.

**Comment by GitTorre** [comment]
I think this is what is needed to overcome this behavior:

{
    "name": "[concat('VMIaaSAntimalware','_vmNodeType0Name')]",
    "properties": {
        "publisher": "Microsoft.Azure.Security",
        "type": "IaaSAntimalware",
        "typeHandlerVersion": "1.5",
        "settings": {
            "AntimalwareEnabled": "true",
            "Exclusions": {
                "Paths": "[concat(parameters('svcFabData'), ';', parameters('svcFabLogs'), ';', parameters('svcFabRuntime'))]",
                "Processes": "Fabric.exe;FabricHost.exe;FabricInstallerService.exe;FabricSetup.exe;FabricDeployer.exe;ImageBuilder.exe;FabricGateway.exe;FabricDCA.exe;FabricFAS.exe;FabricUOS.exe;FabricRM.exe;FileStoreService.exe"
            },
            "RealtimeProtectionEnabled": "true",
            "ScheduledScanSettings": {
                "isEnabled": "true",
                "scanType": "Quick",
                "day": "7",
                "time": "120"
            }
        },
        "protectedSettings": null
    }
}

See https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-best-practices-security#windows-defender

...Charles

**Comment by GitTorre** [comment]
if this fails parsing (invalidElementName or something like that): 

"name": "[concat('VMIaaSAntimalware','_vmNodeType0Name')]", 

then try :

"name": "VMIaaSAntimalware_VMNodeType", where VMNodeType would be like SFRole0, for example.

**Comment by davidleacy** [comment]
For context, myself and Charles had a call where we troubleshooted my issues, there was a couple of issues with my setup primarily:

1. I had a service which was running as System user and listed in my AppObserverConfig, Fabric Observer cannot report on services which have a higher privilege than FO itself, this was generating Warnings in `observer_logs`.
2. I had verbose logging turned on which in almost all cases is not required or recommended when running FO as a customer.
3. The combination of the above is causing Windows Defender to scan very often, looking at Task Manager on my VMs it was clear to see it is Defender and not FO which was causing the CPU spikes.
4. I also had some observers enabled that I wasn't using so that was more of a good to have than anything else.

I am in the process of rolling out the above changes to see if that solves my teams' issues. Shout out to Charles for the great support.

**Comment by GitTorre** [comment]
This should be better in 3.1.16. NodeObserver and AppObserver were opening too many processes due to calling FO's port detection functions in a loop. Apparently, Windows Defender doesn't like this behavior (or something else monitoring FO that MsMpEng.exe than scans). I spent a lot of time investigating what Windows Defender was doing and no exclusion list solved the problem, so I figured the problem must be in FO code. And, apparently, it was. Please let me know if you see improvements in 3.1.15 by disabling NodeObserver. Also, decrease the MonitorDuration for AppObserver to 1 second. 

3.1.16 solves this problem so in that version you can enable NodeObserver. 

For those reading along, this only impacts Windows users and only on lower VM skus (meaning, low core numbers). That said, this was a bug in FO code and thank you David for filing this issue. I am still trying to figure out if their is some magical exclusion that will prevent this from happening in 3.1.15, but have so far come up empty (even when digging into defender runtime logs....). 

Please upgrade to 3.1.16 which will arrive today, 7/29/2021

**Comment by davidleacy** [comment]
Thank Charles for all your help debugging the issue. Great dealing with you.

Upgrading to 3.1.16 has resolved the issue for our team and CPU usage has returned to normal levels.
