### ISSUE TITLE
[FEATURE REQUEST] Monitor and alert on KVS database metrics

### ISSUE THREAD

**Issue by sridmad** [microsoft/service-fabric-observer#188]
**Is your feature request related to a problem? Please describe.**
Provide an observer to monitor KVS database for various metrics and alert on them

**Describe the solution you'd like**
Monitor at least the following metrics
* LVID usage
* Database size

**Describe alternatives you've considered**
These can be done today by manually checking perf counters or examining size of database on nodes

**Comment by GitTorre** [comment]
LVID usage monitoring will ship in the next release, 3.1.23. Database size will require some changes to SF, so will not ship in 3.1.23.
