### ISSUE TITLE
Fabric Observer crashes 0xc0000005 Access violation while searching for Windows Fabric Database counter category

### ISSUE THREAD

**Issue by andrewtyped** [microsoft/service-fabric-observer#209]
**Describe the bug**
FabricObserver crashes repeatedly on _one_ of five nodes with the below pair of errors in Windows event viewer. Reproduced in versions 3.1.23 and 3.1.25 on a standalone Windows Service Fabric cluster at version 7.2.457.9590.

```
Application: FabricObserver.exe
CoreCLR Version: 4.700.22.11601
.NET Core Version: 3.1.23
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFB96651EE7 (00007FFB964C0000) with exit code c0000005.
```
and

```
Faulting application name: FabricObserver.exe, version: 3.1.25.0, time stamp: 0x619ae151
Faulting module name: coreclr.dll, version: 4.700.22.11601, time stamp: 0x620d7666
Exception code: 0xc0000005
Fault offset: 0x0000000000191ee7
Faulting process id: 0xa78
Faulting application start time: 0x01d840697976f54c
Faulting application path: C:\ProgramData\SF\aws-bastian05\Fabric\work\Applications\FabricObserverType_App61\FabricObserverPkg.Code.3.1.25\FabricObserver.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.23\coreclr.dll
Report Id: 83a711cb-8864-44f6-bd1d-bec902d28ffc
Faulting package full name: 
Faulting package-relative application ID: 
```
**To Reproduce**
Deploy FabricObserver 3.1.23 or 3.1.25 to a Service Fabric cluster at version 7.2.457.9590

**Expected behavior**
Fabric Observer runs without crashing. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Windows Server 2016 Datacenter 

**Additional context**
I captured a crash dump which led me to this call stack:

```
 	System.Diagnostics.PerformanceCounter.dll!System.Diagnostics.PerformanceDataRegistryKey.GetValue(string name, bool usePool) Line 65	C#
 	System.Diagnostics.PerformanceCounter.dll!System.Diagnostics.PerformanceMonitor.GetData(string item, bool usePool) Line 1333	C#
 	System.Diagnostics.PerformanceCounter.dll!System.Diagnostics.PerformanceCounterLib.GetPerformanceData(string item, bool usePool) Line 1027	C#
 	System.Diagnostics.PerformanceCounter.dll!System.Diagnostics.PerformanceCounterLib.CategoryTable.get() Line 128	C#
 	System.Diagnostics.PerformanceCounter.dll!System.Diagnostics.PerformanceCounterLib.CategoryExists(string machine, string category) Line 283	C#
 	System.Diagnostics.PerformanceCounter.dll!System.Diagnostics.PerformanceCounterCategory.Exists(string categoryName, string machineName) Line 436	C#
 	System.Diagnostics.PerformanceCounter.dll!System.Diagnostics.PerformanceCounterCategory.Exists(string categoryName) Line 416	C#
>	FabricObserver.dll!FabricObserver.Observers.ObserverManager.IsLVIDPerfCounterEnabled() Line 1247	C#
 	FabricObserver.dll!FabricObserver.Observers.ObserverManager.StartObserversAsync() Line 213	C#
 	FabricObserver.dll!FabricObserver.FabricObserver.RunAsync(System.Threading.CancellationToken cancellationToken) Line 49	C#
 	Microsoft.ServiceFabric.Services.dll!Microsoft.ServiceFabric.Services.Runtime.StatelessService.Microsoft.ServiceFabric.Services.Runtime.IStatelessUserServiceInstance.RunAsync(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.ServiceFabric.Services.dll!Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.ExecuteRunAsync(System.Threading.CancellationToken runAsyncCancellationToken)	Unknown
 	Microsoft.ServiceFabric.Services.dll!Microsoft.ServiceFabric.Services.Runtime.StatelessServiceInstanceAdapter.ScheduleRunAsync.AnonymousMethod__0()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task>.InnerInvoke() Line 518	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task..cctor.AnonymousMethod__274_0(object obj) Line 2428	C#
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread threadPoolThread, System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 289	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot, System.Threading.Thread threadPoolThread) Line 2389	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread threadPoolThread) Line 2327	C#
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread threadPoolThread) Line 2312	C#
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 663	C#
 	System.Private.CoreLib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 29	C#
```

The locals show me we are trying to see if the `Windows Fabric Database` counter category exists. I can confirm it does exist on the affected node, and so does the Long-Value Maximum LVID counter. I am not sure what the environmental difference is that causes observer to fail one just this one node.

I can provide the crash dump in full on request, just need somewhere to upload it.

**Comment by GitTorre** [comment]
Thank you for the bug report. This is interesting. It could be that there is an issue with performance counters (corruption) on that single machine. You may need to manually rebuild them on that machine:  Please [see this doc](https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters) for details. 

Re FO crashing, this should not happen (so, FO should handle this and prevent it from taking the service down. That is a bug in FO. 

In the meantime, just disable this feature. You can do this with a parameter-only versionless application upgrade: 

```PowerShell
$appParams = @{ "AppObserverEnableKvsLvidMonitoring" = "false"; "FabricSystemObserverEnableKvsLvidMonitoring" = "false";  }
Start-ServiceFabricApplicationUpgrade -ApplicationName fabric:/FabricObserver -ApplicationParameter $appParams -ApplicationTypeVersion 3.1.25 -UnMonitoredAuto
```
I will look into preventing this type of issue from taking down FO. This should never crash FO. Thanks for the BUG report. Please repair your VM's perf counters as mentioned and disable this feature in the interim to prevent this from happening again on faulty VMs.

**Comment by GitTorre** [comment]
Please place the zipped dmp in a cloud storage folder (OneDrive, Google Drive, etc.) and share with me.

**Comment by GitTorre** [comment]
This is the unhandled exception that takes the process down:

0xc0000005:

STATUS_ACCESS_VIOLATION | The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

This type of exception is not handled by related code: 

```C#
try
{
    if (!PerformanceCounterCategory.Exists(categoryName))
    {
          return false;
    }
                
    return PerformanceCounterCategory.CounterExists(counterName, categoryName);
}
catch (Exception e) when (e is ArgumentException || e is InvalidOperationException || e is UnauthorizedAccessException || e is Win32Exception)
{
       Logger.LogWarning($"IsLVIDPerfCounterEnabled: Failed to determine LVID perf counter state:{Environment.NewLine}{e}");
}
``` 

Thus the process crash. FO doesn't handle AVs in the surrounding code, either. These are typically signs of issues outside of FO. In this case, the .NET Core runtime and the state of the machine. Something is wrong with the VM. You could try restarting it.

I am not particularly comfortable with catching AccessViolationException as a general rule. FO crashing here is expected given something is wrong with the surrounding environment (so, what other state on the system is corrupted?, etc...).

**Comment by andrewtyped** [comment]
Thank you for the workaround, I can confirm this stopped the process from crashing. The crash dump is available here for the next 7 days: https://1drv.ms/u/s!AmK71g0m06FFvXgKJbUygBmch-iY?e=fvJJFx

I did initially try updating the .net core runtime (latest hosting bundle for 3.1) to see if that fixed the problem, to no effect. Unfortunately this is a production machine so I cannot restart it at will. I will look into rebuilding performance counters if issues re-surface or during our next maintenance window.

Since we have a workaround, and this seems like a temporary setting anyway, feel free to close this issue at will.

**Comment by andrewtyped** [comment]
We are deploying FO with the framework dependent package. This is our strategy in general with net core as it reduces the size of our packages a lot, and speeds up deployments considerably.

**Comment by GitTorre** [comment]
The AV happened in advapi32.dll. I highly encourage you to look into the health of the VM (OS). FO Windows depends on other perf counters (not many) and you may see more issues should more corruption take place. FO does not catch AVs in any general code path. It could be that only the offending perf category is corrupted (for some reason that a process dump won't itself contain). That could change.
