### ISSUE TITLE
[BUG] Deployed fabricobserver failed to start

### ISSUE THREAD

**Issue by harrchen88** [microsoft/service-fabric-observer#219]
**Describe the bug**
Deployed fabricobserver from VS2019 to a SF cluster.  Deploiyment was successful but the fabricObserver failed to start.  
Error information:
Kind,Health State,Description,Source UTC
DeployedApplications,Error,66% (4/6) deployed applications are unhealthy. The evaluation tolerates 0% unhealthy deployed applications, or 0 deployed applications calculated using ceiling.,
   DeployedApplication,Error,Deployed application on node '_NT1dev_6' is in Error.,
       DeployedServicePackages,Error,100% (1/1) deployed service packages are unhealthy.,
           DeployedServicePackage,Error,Service package for manifest 'FabricObserverPkg' and service package activation ID 'bab88c7b-23ef-4148-a37f-ccf0b058d74e' is in Error.,
               Event,Error,'System.Hosting' reported Error for property 'CodePackageActivation:Code:EntryPoint:132997401634938160'.
There was an error during CodePackage activation.The process/container terminated with exit code:2147516547. Please look at your application logs/dump or debug your code package for more details. For information about common termination errors, please visit https://aka.ms/service-fabric-termination-errors,2022-06-23T22:28:10.081Z
   DeployedApplication,Error,Deployed application on node '_NT1dev_1' is in Error.,
       DeployedServicePackages,Error,100% (1/1) deployed service packages are unhealthy.,
           DeployedServicePackage,Error,Service package for manifest 'FabricObserverPkg' and service package activation ID 'e0cc61e8-e916-448f-89b8-53fcf1426c6c' is in Error.,
               Event,Error,'System.Hosting' reported Error for property 'CodePackageActivation:Code:EntryPoint:132998267648180683'.
There was an error during CodePackage activation.The process/container terminated with exit code:2147516547. Please look at your application logs/dump or debug your code package for more details. For information about common termination errors, please visit https://aka.ms/service-fabric-termination-errors,2022-06-23T22:28:09.521Z
   DeployedApplication,Error,Deployed application on node '_NT1dev_2' is in Error.,
       DeployedServicePackages,Error,100% (1/1) deployed service packages are unhealthy.,
           DeployedServicePackage,Error,Service package for manifest 'FabricObserverPkg' and service package activation ID '91201a40-6634-4fa0-864f-f9e157eaf287' is in Error.,
               Event,Error,'System.Hosting' reported Error for property 'CodePackageActivation:Code:EntryPoint:132998269800889650'.
There was an error during CodePackage activation.The process/container terminated with exit code:2147516547. Please look at your application logs/dump or debug your code package for more details. For information about common termination errors, please visit https://aka.ms/service-fabric-termination-errors,2022-06-23T22:28:08.460Z
   DeployedApplication,Error,Deployed application on node '_NT1dev_3' is in Error.,
       DeployedServicePackages,Error,100% (1/1) deployed service packages are unhealthy.,
           DeployedServicePackage,Error,Service package for manifest 'FabricObserverPkg' and service package activation ID '06ee7051-e3e7-4132-9fe2-c36adb2d699f' is in Error.,
               Event,Error,'System.Hosting' reported Error for property 'CodePackageActivation:Code:EntryPoint:132998271481738610'.
There was an error during CodePackage activation.The process/container terminated with exit code:2147516547. Please look at your application logs/dump or debug your code package for more details. For information about common termination errors, please visit https://aka.ms/service-fabric-termination-errors,2022-06-23T22:28:11.266Z

**To Reproduce**
Clone the repo, open the solution from VS 2019, publish the fabricobserver to the SF cluster (6 nodes).  The cluster version is 9.0.1028.9590

**Expected behavior**
Expected the fabricobserver starts successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/39616938/175426686-28b9babf-c96a-4b9c-9cf2-beeda459853d.png)

windows 10 desktop for developer machine.

**Additional context**

**Comment by GitTorre** [comment]
Hi,

How are you deploying the application from Visual Studio? Are you sure the .NET Core 3.1 runtime is in the deployed code package?

**Comment by GitTorre** [comment]
If you publish from VS, then you for sure need to modify the FabricObserver.csproj file and uncomment the RuntimeIdentifier section (and comment out the RuntimeIndentifiers section, which applies to building for windows and linux – this is what is breaking your deployment). 

Try this:  
 ```XML
             <!-- ***NOTE***: If deploying to SF cluster directly from Visual Studio, you must use single target RID:
             For Windows, use win-x64. For Linux, use linux-x64. -->

             <RuntimeIdentifier>win-x64</RuntimeIdentifier> 
             
             <!-- For multi-target publish (say, from Azure Pipeline build or for when you build FO using supplied scripts), you can use multi-target RIDs: linux-x64;win-x64.
             <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers> -->
```
