### ISSUE TITLE
[BUG] ClusterObserver not building

### ISSUE THREAD

**Issue by levimatheri** [microsoft/service-fabric-observer#253]
**Describe the bug**
The ClusterObserver project is not building. Here's the error I'm seeing when I run the `Build-ClusterObserver.ps1` script:
```
D:\a\1\s\ClusterObserver\ClusterObserverManager.cs(93,17): error CS0104: 'Logger' is an ambiguous reference between 'ClusterObserver.Utilities.Logger' and 'FabricObserver.Observers.Utilities.Logger' [D:\a\1\s\ClusterObserver\ClusterObserver.csproj]
Copy-Item : Container cannot be copied onto existing leaf item.
```
Also noticed `ClusterIdentificationUtility.cs` [is removed from compilation](https://github.com/microsoft/service-fabric-observer/blob/b2674d43bfe057b0e22774568e4398a641401411/ClusterObserver/ClusterObserver.csproj#L24). Is this intentional? Because it's also causing errors when trying to build.

**To Reproduce**
Run `Build-ClusterObserver.ps1` script
**Expected behavior**
Should build ClusterObserver with no errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
SFObserver version 3.2.2.831

**Comment by GitTorre** [comment]
Hi,

Are you just running the script from the latest sources (main)? 

ClusterIdentificationUtility lives in TelemetryLib, not in the ClusterObserer project. Logger lives in FabricObserver.Extensibility.dll.

The only way you would hit these errors is if you are building an older version of CO against the most recent version of FOExtensibility. That would be incompatible. 

Can you let me know how you have your solution configured? That is, are you simply cloning main, then running this script? I don't see how that would lead to these results as the latest version of CO references the Extensibility project (and TelemetryLib). Also, CO is built this way (running the build script) in the release pipeline. It would have failed if there was some bug in the script or the project configuration.

**Comment by levimatheri** [comment]
@GitTorre My bad, I had initially copy-paste-overwritten my existing project (earlier version), and must have messed things up. I just ran the build script off of the new version and it works just fine. 

Thanks.
