### ISSUE TITLE
[BUG] log directory calculation in FabricObserver.Extensibility/Utilities/DataTableFileLogger.cs, ConfigureLogger is faulty

### ISSUE THREAD

**Issue by gopueurclr** [microsoft/service-fabric-observer#269]
**Describe the bug**
When `BaseDataLogFolderPath` contains a full path *with a drive*, `ConfigureLogger` does not set
the local variable `logBasePath` correctly.
This causes the logging to not the respect the path intended by `BaseDataLogFolderPath`.
(We need to specify the drive because we need to log to a drive other than `C:` as per the company policy.)

**To Reproduce**
Set `ObserverManagerConfiguration/DataLogPath` in `Settings.xml` to (example): `D:\mypath`. Logs will go to `C:\fabric_observer_csvdata`

**Expected behavior**
Logs should be under `D:\mypath`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version N/A

**Additional context**

This code in ConfigureLogger:

`           
            if (!string.IsNullOrWhiteSpace(BaseDataLogFolderPath))
            {
                if (OperatingSystem.IsWindows())
                {
                    // Add current drive letter if not supplied for Windows path target.
                    if (!BaseDataLogFolderPath.Substring(0, 3).Contains(":\\"))
                    {
                        string windrive = Environment.SystemDirectory.Substring(0, 3);
                        logBasePath = windrive + BaseDataLogFolderPath;
                    }
                }
`

should be for example

`           
            if (!string.IsNullOrWhiteSpace(BaseDataLogFolderPath))
            {
                if (OperatingSystem.IsWindows())
                {
                    // Add current drive letter if not supplied for Windows path target.
                    if (!BaseDataLogFolderPath.Substring(0, 3).Contains(":\\"))
                    {
                        string windrive = Environment.SystemDirectory.Substring(0, 3);
                        logBasePath = windrive + BaseDataLogFolderPath;
                    }
                    else
                    {
                        logBasePath = BaseDataLogFolderPath;
                    }
                }
`

(Other variants to achieve the same are possible).

**Comment by GitTorre** [comment]
Fix is in develop branch. Can you test it out in your Test environment?

**Comment by gopueurclr** [comment]
Hi,

we tested it over here, I confirm it works as intended.

For me, the issue can be closed.

**Comment by GitTorre** [comment]
Thank you for validating. This will ship as part of the 3.2.7 release.
