### ISSUE TITLE
[FEATURE REQUEST] Make telemetry parameters configurable in application parameters

### ISSUE THREAD

**Issue by negberts** [microsoft/service-fabric-observer#292]
**Is your feature request related to a problem? Please describe.**
Telemetry parameters like TelemetryProvider and LogAnalyticsWorkspaceId are currently not available in de application manifest XML and can therefore not be overridden when the application is deployed.

**Describe the solution you'd like**
Make the telemetry parameters available in ApplicationManifest.xml

**Comment by GitTorre** [comment]
This will ship in 3.2.14. This is a breaking change for existing Telemetry settings that exist in Settings.xml today. Those settings will need to be overridden in ApplicationManifest.xml, so that related App parameters will host the setting values, specified in their DefaultValue attributes. Both Settings.xml and ApplicationManifest.xml will be commented to reflect this to make sure it is understood.

**Comment by negberts** [comment]
@GitTorre thanks. Shouldn't the ClusterObserverApp application manifest XML be updated as well? In your commit I see only changes in the FabricObserverApp

**Comment by GitTorre** [comment]
Yes. We will update CO as well. The feature is still in development and testing. Thanks for the reminder.

**Comment by GitTorre** [comment]
@negberts  CO support pushed to develop. Please give it a try (CO and FO) if you have time. Ensure it works for your scenarios (it should).

**Comment by negberts** [comment]
@GitTorre looks good to me! :-)

**Comment by negberts** [comment]
@gittorre Thank you for implementing this. Are the assets for cluster observer missing in the release?

**Comment by GitTorre** [comment]
Yes. Will correct. Sorry about that.

**Comment by GitTorre** [comment]
@negberts CO SFpkgs uploaded to Release.

**Comment by negberts** [comment]
@gittorre some observations:

In Application Insights all health events are logged with state Invalid:

![image](https://github.com/microsoft/service-fabric-observer/assets/20299260/8be42dcd-bcdd-4dec-ac0c-b554fd67ef69)

Probably because Invalid is 0 and Ok = 1 in the enum... I should expect them to be logged as Ok.

And it would be nice if we had some loglevel setting that only warnings and errors would be sent to application insights / log analytics so we can create alerts.

**Comment by GitTorre** [comment]
These are raw metric data events. HealthState of the related entity is not considered. If the metric value meets or exceeds a specified threshold, then you will see Warning or Error or Ok events in the case where the usage has gone below the threshold in a subsequent run. This is by-design behavior.

If you don't want raw telemetry, then, yes, a new setting would need to be added to only emit telemetry that carries HealthState, so only when an entity is in Warning, Error or has recovered. That would mean you wouldn't be able to query for usage over time, which is useful to do. However, if the concern is telemetry volume, a valid concern, then adding such a pre-filter is useful. You would need to be comfortable only getting Warning/Error and recovery (as Ok) telemetry. Nothing prevents you from creating alerts today as unhealthy events are emitted in addition to raw telemetry.

**Comment by negberts** [comment]
Aren't the events also stored in Azure Storage? Because yes, the concern is the telemetry volume...  So than we can say that the raw telemetry is still in Azure Storage and the unhealthy events are only in Application Insights/Log Analytics? Would be a nice feature for me...

**Comment by GitTorre** [comment]
These events are not also present in storage account. These are specifically LogAnalytics or ApplicationInsights telemetry events, depending upon your configuration.

**Comment by GitTorre** [comment]
@negberts This feature is available in develop branch if you want to check it out. You can disable metric telemetry data for 5 observers individually in ApplicationManifest.

**Comment by negberts** [comment]
@gittorre wow thanks :-) Next week on holidays but will check it out after that!

**Comment by negberts** [comment]
@gittorre took me some time, but looks good to me :-)
