### ISSUE TITLE
issue NeworkUsage.cs TupleGetDynamicPortRange  Unhandled exception in GetSystemCpuMemoryValuesAsync with 4 digit 'start port'

### ISSUE THREAD

**Issue by jagilber** [microsoft/service-fabric-observer#33]
issue NeworkUsage.cs TupleGetDynamicPortRange  Unhandled exception in GetSystemCpuMemoryValuesAsync with 4 digit start port

C:\r>netsh int ipv4 show dynamicportrange tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 1024 <---- 4 digit number causing substring offset to be wrong
Number of Ports : 64511

2020-01-16 12:16:52.8537--WARN--FabricObserver service health warning: fabric:/FabricObserver/FabricObserver | NodeObserver | Unhandled exception in GetSystemCpuMemoryValuesAsync: Input string was not in a correct format.: 
    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at FabricObserver.Utilities.NetworkUsage.TupleGetDynamicPortRange(Protocol protocol) in C:\github\Microsoft\service-fabric-observer\FabricObserver\Observers\Utilities\NetworkUsage.cs:line 242
   at FabricObserver.Utilities.NetworkUsage.GetActiveEphemeralPortCount(Int32 procId, Protocol protocol) in C:\github\Microsoft\service-fabric-observer\FabricObserver\Observers\Utilities\NetworkUsage.cs:line 318
   at FabricObserver.NodeObserver.<>c__DisplayClass61_0.<GetSystemCpuMemoryValuesAsync>b__0() in C:\github\Microsoft\service-fabric-observer\FabricObserver\Observers\NodeObserver.cs:line 268

proposed fix:
                    Match match = Regex.Match(output,
                        @"Start Port\s+:\s+(?<startPort>\d+).+?Number of Ports\s+:\s+(?<numberOfPorts>\d+)",
                        RegexOptions.Singleline | RegexOptions.IgnoreCase);

                    string startPort = match.Groups["startPort"].Value;
                    string portCount = match.Groups["numberOfPorts"].Value;

verification:
	OSObserver	MachineInformation	Thu, 16 Jan 2020 14:11:48 GMT	0.00:01:27.0	132236575080657285	true	false
OS Information:

Name: Microsoft Windows 10 Enterprise
Version: 10.0.18363
InstallDate: 2019-07-16T13:51:22.0000000Z
LastBootUpTime*: 2020-01-14T23:06:34.5000000Z
OSLanguage: 1033
OSHealthStatus*: OK
NumberOfProcesses*: 461
WindowsEphemeralTCPPortRange: 1024 - 65535 (Active*: 148)
FabricApplicationTCPPortRange: 30001 - 31000
ActiveFirewallRules*: 501
TotalActiveTCPPorts*: 155

Hardware Information:

LogicalProcessorCount: 8
TotalVirtualMemorySize: 37 GB
TotalVisibleMemorySize: 31 GB
FreePhysicalMemory*: 15.47 GB
FreeVirtualMemory*: 10.4 GB
LogicalDriveCount: 1
Drive C (System) Size: 952.77 GB
Drive C (System) Consumed*: 70%

Windows Patches/Hot Fixes*:
...

creating pr if you want it but np if you dont

**Comment by GitTorre** [comment]
Thank you for finding and fixing this bug. Much appreciated. I will merge you PR.
