### ISSUE TITLE
Telemerty Filtering

### ISSUE THREAD

**Issue by joshua-pappalardo** [microsoft/service-fabric-observer#48]
If both AppObserver and OSObserver are reporting telemetry to Application Insights, There does not appear to be a property to be able to determine which observer generated the telemetry. Also AppObserver Telemetry provides no mechanism to discern which application the telemetry is for. The only thing that can be done is narrow down the results for a particular node.

**Comment by GitTorre** [comment]
Thank you for the feedback. Yes, Ai Telemetry data is not as fully structured as LogAnalytics and the implementation needs to be improved to make it more queryable. This is on my to-do list. Will mark this as Feature request, but frankly it's also kind of a bug for the reasons you outline. Parsing a string is not a great way to do diagnostic analysis... On it.

**Comment by GitTorre** [comment]
![image](https://user-images.githubusercontent.com/6273411/77211322-e0712d00-6ac0-11ea-8909-07ce64eb537c.png)

How's that?

**Comment by GitTorre** [comment]
Thoughts on this type of query experience?

customEvents | where customDimensions["HealthEventDescription"] != "N/A" 
and customDimensions["Application"] == "fabric:/CpuStress"
and customDimensions["HealthState"] == "Warning"

**Comment by joshua-pappalardo** [comment]
That looks like it would give us what we need. I greatly appreciate the quick response

**Comment by GitTorre** [comment]
Cool. I won’t ship this until I do more testing. So, sometime this weekend. Thanks again for reaching out.

**Comment by GitTorre** [comment]
Fixed. Tested. Merged.

**Comment by GitTorre** [comment]
See release notes: https://github.com/microsoft/service-fabric-observer/releases/tag/29640846
