### ISSUE TITLE
Automated deployment approach

### ISSUE THREAD

**Issue by markwragg** [microsoft/service-fabric-observer#58]
Hi,

I'm setting up an Azure DevOps pipeline to deploy Service Fabric Observer in our environment. I wanted to validate (at a high level) the approach i'm considering in case you can see any flaws in it. I am doing the following:

Placing the SignedCO.sfpkg and SignedFO.sfpkg files in my repo (which is then built as an artifact) under different subdirectories. I have then renamed these to .zip and copied from them the /config directories (and the .config files from the code directory of FabricObserver). I'm storing these files in a directory alongside the zip.

I then rename the sfpkg.zip files back to sfpkg. I now plan to customise my copies of the configuration files to my requirements.

In my pipeline I do the following:

- Rename the .sfpkg files to sfkpkg.zip
- Extract the sfpkg.zip files
- Copy my versions of the config files over the default equivalents in the extracted packages
- Deploy the applications

Does this seem like a reasonable approach? Am I overcomplicating things? I'm trying to make it so that when new versions are released I'll just have to drop the new sfpkg files into my repo, but I appreciate i'd also need to look for breaking changes to the structure/content of the default config files.

Thanks in advance.

**Comment by GitTorre** [comment]
Assuming you have tested this, but it looks good to me as there is currently no other way to add customized configs/param settings during deployment. That remains a work item for us. Your approach should work and you are not overthinking it. It’s simple to rename, decompress, copy over customized configs, compress, rename to sfpkg, deploy the sfpkgs.

**Comment by GitTorre** [comment]
And thank you in advance for using these observability tools. If you have any questions, just ask.

**Comment by markwragg** [comment]
That's great thanks for the quick feedback. I'm just testing it now and its certainly looking like a working solution.
