### ISSUE TITLE
Info on "Windows Update" setting

### ISSUE THREAD

**Issue by ChiragPavecha** [microsoft/service-fabric-observer#59]
Would be great if we can add Banner/Warning/Link to clusters where Windows Update is still enabled and potentially causing VM’s to reboot unexpectedly.  Link in banner pointing to recommended SF configuration for VMSS OS Updates or POA

**Comment by GitTorre** [comment]
Thanks for the feature request. Yes, this is something that OSObserver could look for and, if detected, emit an informational health event that contains a link to related documentation much as it does today with links to kb articles about OS updates/patches that have been installed on the VM it's running on. This information would also reside in the structured telemetry data OSO emits.

**Comment by GitTorre** [comment]
How about this?
![CaptureAUFO](https://user-images.githubusercontent.com/6273411/80891575-c0b15500-8c79-11ea-85d1-0d32a7a831e1.PNG)

**Comment by sridmad** [comment]
May be create a different health event specifically for Windows Updates related information so they can be marked as warning and/or error as the case may be.

Auto Windows update enabled should always be a warning in SF scenarios - Use automatic Image update or POA (for bronze durability)

Warnings if OS updates are not installed after a grace period?

**Comment by GitTorre** [comment]
@sridmad Yes, if it should be a warning, then I will generate one if AU service is enabled. 

In terms of OS update grace period expiration warnings, that should really be something POA does, as it is already configurable for that type of thing, for example. I'm not sure FO should join the WU game. For stuff like AU detection, that's easy. For monitoring updates, generally, this will add redundancy if POA is installed. FO doesn't orchestrate patching and as such warning users that an update must take place due to some grace period expiration makes more sense in the service that orchestrates patching.

**Comment by GitTorre** [comment]
Pushed change to develop. It's not ready for merge into master (code refinement/refactoring/review, more testing). You can pull latest from there and test it out. I will merge into master and produce signed builds early next week. Let me know what you think.

**Comment by GitTorre** [comment]
Pull latest from develop. The first impl was too aggressive.

**Comment by GitTorre** [comment]
![CaptureAUFO](https://user-images.githubusercontent.com/6273411/81025024-293f3400-8e2a-11ea-92a4-47d0bbba6105.PNG)

**Comment by markwragg** [comment]
I think this should be reopened. Currently the code does the following check for if Windows Updates are enabled (which is if the service is enabled then the setting must be "notify before download":
```
   this.isWindowsUpdateAutoDownloadEnabled =
                    wuLibAutoUpdates.ServiceEnabled &&
                    wuLibAutoUpdates.Settings.NotificationLevel != AutomaticUpdatesNotificationLevel.aunlNotifyBeforeDownload;
```

In my environment, the service is enabled but Windows Update is set to "never check for updates". I think the above check should be amended to include that as an acceptable sign that Windows updates are disabled (the enum to check I believe would be `AutomaticUpdatesNotificationLevel.aunlDisabled`).

**Comment by markwragg** [comment]
@GitTorre did you see my update on this above? ^

**Comment by markwragg** [comment]
Created a new issue for this as I think it makes more sense/easier to relate to the next release.
