### ISSUE TITLE
DiskObserver Events do not indicate a drive letter or ID

### ISSUE THREAD

**Issue by markwragg** [microsoft/service-fabric-observer#60]
Hi,

I'm looking at the DiskObserver events in AppInsights and it seems like it is giving me events for the individual disks, but doesn't include any way to determine which drive ID or Letter they are for. Could the output of DiskObserver be amended to include that?

I can see individual drive letters under the DriveInfo property of the OSObserver events but obviously this isn't particularly easy to graph from.

I am quite new to AppInsights so if i'm just missing something in the existing output of DiskObserver please let me know.

Thanks,
Mark

**Comment by GitTorre** [comment]
Thank you. Let me look into this. Will reply with more detail soon.

**Comment by GitTorre** [comment]
I see the problem... Great catch. Will this work for you?

![CaptureDiskObsAi](https://user-images.githubusercontent.com/6273411/81019938-977cfa00-8e1c-11ea-9c31-533231d327b5.PNG)

**Comment by markwragg** [comment]
Yes that would be great!

**Comment by GitTorre** [comment]
This will ship in the next release, which I will ship this week (sooner rather than later, so in the next day or so).

**Comment by markwragg** [comment]
This is working great in 2.0.6. Here's an AppInsights query i'm now using to chart disk space:
```
customEvents
| where timestamp > ago(7d)
| where name == "DiskObserverDataEvent" and customDimensions["Metric"] contains "D: Disk Space Available MB"
| where customDimensions["NodeName"] contains 'node0'
| summarize avg(round(todecimal(customDimensions["Value"]) / 1024, 2)) by bin(timestamp, 15m), tostring(customDimensions["NodeName"])
| render timechart with (ymin=0, ytitle='Free DiskSpace in GB (D:)')
```
