### ISSUE TITLE
NetworkObserver: Filter duplicate endpoints before testing

### ISSUE THREAD

**Issue by markwragg** [microsoft/service-fabric-observer#62]
As discussed in #61, sometimes multiple applications connect to the same endpoint. As such in the `NetworkObserver.config.json` file the same endpoint may be declared for multiple applications. 

Its desirable for all of those applications to show a warning state when that endpoint is unavailable, but wasteful for NetworkObserver to check those endpoints more than once on each invocation, so it would be a good enhancement to have NetworkObserver filter out those duplicates before it performs testing.

**Comment by GitTorre** [comment]
This has been pushed to develop. Thanks again for all the great feedback!
