### ISSUE TITLE
FabricObserver.dll not signed in the released sfpkg

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#84]
Please close this if I've made a mistake but it appears the FabricObserver.dll is not signed. 

Cluster observer seems OK.

Thanks

**Comment by adamtickner** [comment]
Version 3.0.9

**Comment by GitTorre** [comment]
Will check. Thanks for reporting.

**Comment by GitTorre** [comment]
Yeah. Somehow that Pipeline task went missing. My apologies. Running another build now. Appreciate the headsup.
...Charles

**Comment by GitTorre** [comment]
![image](https://user-images.githubusercontent.com/6273411/97769462-920d1d80-1ae8-11eb-85cb-3b3e1afa51f5.png)
 Fixed. Thanks again!

**Comment by adamtickner** [comment]
Thank you!
