### ISSUE TITLE
What is the best way to debug plugins?

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#87]
Hi

What is the best process is to debug plugins that have been dropped in the plugin folder and loaded dynamically?

Thanks, Adam

**Comment by GitTorre** [comment]
Hi,

Build your plugin project in debug.
Deploy FO to your local dev cluster with your debug plugin dll in the Plugins folder.

From your plugin project VS instance in Debug mode:

Set break points..
Launch a debugger via Attach to Process.
Attach to FabricObserver.exe.
Debug.

**Comment by adamtickner** [comment]
OK - that is what I was doing but having some trouble.

Will give it another go. Thanks for clarifying we're on the right track.
