### ISSUE TITLE
Cluster observer releases

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#90]
Hi Charles

Just wondering if you'll be adding the cluster observer as a github release (and maybe the FO web api?)

Thanks again!

**Comment by GitTorre** [comment]
Hi,

Yes. I will release an updated build of CO. For the web app, I will make sure it's up to date and still works as expected. Give me a day.

Thanks for asking!

**Comment by GitTorre** [comment]
CO 2.0.2 with signed binaries: https://github.com/microsoft/service-fabric-observer/releases/tag/36711882

**Comment by adamtickner** [comment]
Nice, thanks
