### ISSUE TITLE
sfpkg version not matching release version

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#91]
Hi Charles

First, just want to say thank you for answering me so quickly on the issues this week. Please let me know if you aren't able to get to all of these and I'll try and hold off. Just trying to get this up and running in production!

I'm automating downloading the sfpkg files, then applying our plugins + deploying. It seems something odd is happening for this though. The released source zip looks correct, but the sfpkg has 3.0.10 as the application version, but 3.0.9 as the service manifest version.

I also see that when using this sfpkg, I get runtime errors when trying to use the partition Id on the health report so I think something funky has gone on with the build/release there.

Thank you

**Comment by GitTorre** [comment]
Hmm. I will take a look tomorrow, Seattle time.

**Comment by GitTorre** [comment]
I see 3.0.10 as the servicemanifest version inside the sfpkgs. These just contain build output in a specific folder structure. The versioning of the content is not modified by the build process. Can you let me know what you are doing in your automation?

**Comment by adamtickner** [comment]
My apologies. Thought I'd confirmed this manually but I must have made a mistake. 

I've found an issue with the scripting. Sorry!
