### ISSUE TITLE
App insights cluster observer event name not set as expected

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#92]
Hi Charles

For cluster observer telemetry to app insights I am not seeing the event name set as expected. I think this is because in the App insights ReportHealthAsync function it does the following:

`$"{telemetryData.ObserverName ?? "ClusterObserver"}DataEvent"` but the calling code will do a null check before this and send in an empty string. 

Looks like the following:

![image](https://user-images.githubusercontent.com/5872717/99919035-f5e4d800-2d6e-11eb-86f6-625fcf8c7080.png)

Thanks!

**Comment by GitTorre** [comment]
Thanks. Indeed, an empty string is passed to this function... The solution is simple. All data events from CO should be ClusterObserverDataEvent named (there is no reason to do anything else).. I will make this change. Thanks again for using these tools and providing feedback and bugs! 

...Charles

**Comment by GitTorre** [comment]
https://github.com/microsoft/service-fabric-observer/releases/tag/37040664
